export const INCREMENT_COUNTER = '@@Counter/INCREMENT_COUNTER';
export const DECREMENT_COUNTER = '@@Counter/DECREMENT_COUNTER';

export const FETCH_SCORES_STARTED = '@@API/Scores/FETCH_SCORES_STARTED';
export const FETCH_SCORES_SUCCESS = '@@API/Scores/FETCH_SCORES_SUCCESS';
export const FETCH_SCORES_ERRORED = '@@API/Scores/FETCH_SCORES_ERRORED';
